### PR TITLE
feature: Implementing Local Security Features

### LINKED ISSUE #133: Feature: Implement Local Security Features
## Description

As a user, I want to have robust security features so that my account and data remain protected, and I can securely access my application with convenience.

The security system should support the following operations:

- Remember me
- Face ID
- Biometric ID
- Google Authenticator
- Change PIN

### Acceptance Criteria

- [x] Users can enable or disable the "Remember me" option during login
- [x] Users can set up and use Face ID for authentication
- [x] Users can set up and use Biometric ID for authentication
- [x] Users can set up and use Google Authenticator for two-factor authentication
- [x] Users can change their PIN for account access

## Developer Notes

- Implement the "Remember me" feature with secure storage of session tokens
- Integrate with device-specific Face ID and Biometric ID APIs
- Integrate with Google Authenticator using TOTP (Time-based One-Time Password)
- Provide a secure interface for users to change their PIN
- Ensure all sensitive data is encrypted and securely handled
- Implement appropriate error handling and validation for security operations
- Follow best practices for user authentication and security

## Related Issues

- #120 (Profile and Settings Management)

### PR DESCRIPTION
**Pull request by 911samuel**
#### What does this PR do?
This PR implements local security features in the Medica app to enhance user account protection and provide convenient access through biometric authentication and other security options.

#### Description of Task to be completed?
- Implement "Remember me" functionality for persistent login sessions.
- Integrate biometric authentication (Face ID and/or Biometric ID) using Expo Local Authentication.
- Implement PIN change functionality for enhanced account security.

#### How should this be manually tested?
1. Navigate to the Security section in the app settings.
2. Toggle the "Remember me" option and verify if login sessions persist across app restarts.
3. Enable Face ID and Biometric ID authentication options and verify if they work correctly on supported devices.
5. Enable PIN authentication options and verify if they work correctly on supported devices.

### CODE REVIEW

**Review by Emmyfrank — CHANGES_REQUESTED** [review]
The pin can't be changed when you click on change pin nothing cange , and ather , you have to upgrade your branch

autha

**Comment by 911samuel** [comment]
> The pin can't be changed when you click on change pin nothing cange , and ather , you have to upgrade your branch
> 
> autha

@Emmyfrank  where did you got that screen check the branch again
WhatsApp Image 2024-07-12 at 16 55 16


i removed change PIN cause we don't have any screen for changing PIN

**Review by justinmihigo — APPROVED** [review]
It's working on my end saving the info that i used to login in

**Review by Latiah — APPROVED** [review]

**Comment by Emmyfrank** [comment]
> > The pin can't be changed when you click on change pin nothing cange , and ather , you have to upgrade your branch
> > autha
> 
> @Emmyfrank where did you got that screen check the branch again WhatsApp Image 2024-07-12 at 16 55 16
> 
> i removed change PIN cause we don't have any screen for changing PIN

ok now everything is cool you can have my review

**Review by Emmyfrank — APPROVED** [review]

**Review by Emmyfrank — APPROVED** [review]
good job

**Review by twizerim — APPROVED** [review]

**Pull request merged**
