### PR TITLE
Feature: Contact help center

### LINKED ISSUE #68: Feature: Contact Help Center
This issue contains screens of the help center where a user will contact for help through social medias and messages

A user will be able to communicate to the support team regarding problems encountered from the app's services like having problem paying or booking an appointment and other problems that may be rise while using the app

### PR DESCRIPTION
**Pull request by Latiah**
What does this PR do?
This PR includes designs of the help center contact where a user will contact the help center if there is an issue encountered while using the app

Description of Task to be completed?

Design Help center settings screens
Design customer Service chatting app

How should this be manually tested?

Navigate to the home page and click on the profile tab and on that page you will click on the help center and that's where find the help center 

Any background context you want to provide?
N/A

What are the relevant pivotal tracker/Trello stories?
N/A

### CODE REVIEW

**Review by mukunzidd — CHANGES_REQUESTED** [review]
Good job on this @Latiah

Here's a few things you need to improve before you get approved.
- The message text input need to stick to the bottom of the page when the keyboard is not in view
- Make the text input auto-focused when you open the support chat.
- Don't link other methods of support to the chat page. Make then links that open Whatsapp, IG, etc
- The "FAQs" are different from "Contact Us", FAQs are fixed and pre-written but they are not there. 

Simulator Screenshot - iPhone 15 Pro Max - 2024-05-24 at 12 59 06

Simulator Screenshot - iPhone 15 Pro Max - 2024-05-24 at 12 54 52

**Comment by Latiah** [comment]
> Good job on this @Latiah
> 
> Here's a few things you need to improve before you get approved.
> 
> * The message text input need to stick to the bottom of the page when the keyboard is not in view
> * Make the text input auto-focused when you open the support chat.
> * Don't link other methods of support to the chat page. Make then links that open Whatsapp, IG, etc
> * The "FAQs" are different from "Contact Us", FAQs are fixed and pre-written but they are not there.
> 
> Simulator Screenshot - iPhone 15 Pro Max - 2024-05-24 at 12 59 06
> 
> Simulator Screenshot - iPhone 15 Pro Max - 2024-05-24 at 12 54 52

I have worked on these comments please check again.

**Review by chrysloi — APPROVED** [review]
Good job @Latiah!

**Review by chrysloi — CHANGES_REQUESTED** [review]
you should consider working on the search bar to fit the width on the FAQs

**Comment by Latiah** [comment]
> you should consider working on the search bar to fit the width on the FAQs

yes let me do that .Thanks

**Review by 911samuel — CHANGES_REQUESTED** [review]
101_Light_settings help center FAQ-1

Add all items as it on figma design, i can only see to two item on FQA 

WhatsApp Image 2024-05-31 at 09 22 21

**Review by twizerim — APPROVED** [review]

**Review by justinmihigo — APPROVED** [review]
Looks good on my end

**Review by 911samuel — APPROVED** [review]
Great

**Review by fredshema — APPROVED** [review]

**Pull request merged**
