### PR TITLE
Feature: Comprehensive Video Call Feature Enhancement #61

### LINKED ISSUE #61: Feature: Comprehensive Video Call Feature Enhancement
Enhance the video call functionality with a comprehensive set of features that include the ability to see all available doctors for video calls, detailed video call history, playback of video call recordings, and an extended options menu for managing video call history.

### PR DESCRIPTION
**Pull request by 911samuel**
### What does this PR do?

This pull request enhances the video call functionality by introducing a comprehensive set of features:

- **Available Doctors:** Users can now view all available doctors for video calls.
- **Detailed Call History:** Users have access to detailed video call history.
- **Playback:** Users can playback video call recordings.
- **Extended Options Menu:** An extended options menu is provided for managing video call history.

### Description of Task to be completed?

The tasks completed in this pull request include:

- Implementing a screen to display all available doctors for video calls.
- Adding a detailed video call history screen.
- Implementing playback functionality for video call recordings.
- Extending the options menu to manage video call history, including features like download and delete.

### How should this be manually tested?

To manually test this pull request:

1. Open the application and navigate to the video call screen.
2. Verify that all available doctors are displayed with their details.
3. Navigate to the video call history screen and verify that detailed call history is visible.
4. Play back video call recordings to ensure playback functionality is working as expected.
5. Access the extended options menu and test features like download and delete to manage video call history.

### Any background context you want to provide?

The enhancements aim to improve the user experience of the video call feature by providing more functionality and flexibility in managing video calls and call history.

### Screenshots 

Image 3
Image 2
   Image 1

### Questions:

If there are any questions or concerns regarding the implementation or testing of these features, please let us know for further discussion.

### CODE REVIEW

**Review by chrysloi — CHANGES_REQUESTED** [review]
I am not being able to continue.

https://github.com/atlp-rwanda/commanders-rn-medica/assets/99283140/f32de875-77a6-4375-9456-a9182b84bfd4

**Comment by 911samuel** [comment]
> I am not being able to continue.
> 
>  az_recorder_20240526_083812.mp4

Thank you @chrysloi  you can recheck i fixed the errorr

**Review by justinmihigo — COMMENTED** [review]
change the font of the 30:00 time on the seeker and also if you chose to go with it the background of already played part video should be blue, and also find another way to close the modal of menu instead of clicking on download button or delete button after that I think everything will be cool you can reach out so that I can approve this

**Comment by 911samuel** [comment]
> change the font of the 30:00 time on the seeker and also if you chose to go with it the background of already played part video should be blue, and also find another way to close the modal of menu instead of clicking on download button or delete button after that I think everything will be cool you can reach out so that I can approve this

Hello mr @justinmihigo  thank you I didn't that i used different fontsize on timestamp i'm with correcting it, and i also add the way of exiting modal by pressing again the button, on the the played part is already set to blue but it increase as time increase take alook on this photo 🤝
WhatsApp Image 2024-05-27 at 13 37 26

**Review by justinmihigo — APPROVED** [review]
Awesome looks great on my end

**Review by chrysloi — APPROVED** [review]
Good work @911samuel!

**Review by Latiah — APPROVED** [review]

**Review by twizerim — APPROVED** [review]

**Review by Emmyfrank — CHANGES_REQUESTED** [review]
you have nice work , but it would be better if someone try to make a video call, and bring exactly image of someone who is calling instead of bringing constant image.

**Comment by 911samuel** [comment]
> you have nice work , but it would be better if someone try to make a video call, and bring exactly image of someone who is calling instead of bringing constant image.

thank you! but it will be a recorded video that will be playing so it don't need to be a photo and i have changed from a photo to playing video with all functionalities

**Review by Adadie — CHANGES_REQUESTED** [review]
Awesome work on this @911samuel. Just a few things you could improve before we merge this.

1. The time listed on the previous screen before you play the video should match the actual length of the video. It says 30 minutes yet the video is 1:48
2. The back button when playing the video is not that visible. Consider increasing the height of the video frame to fill the entire screen or bring the icon down into the video. If none of this works change the icon color to black and take it at the top, in the white background.
3. I should be able to fast-forward and back from the progress bar

**Comment by Adadie** [comment]
Awesome work @911samuel

**Pull request merged**
