### PR TITLE
Feature: Notifications Implementation

### LINKED ISSUE #151: Feature: Notifications Implementation
**Description**

Notifications from activities taking place in the app like when an appointment is booked or when it is cancelled.

**Tasks**

Integrate the notifications feature on the app.

**Developer Notes**
N/A

**Related Issues**
N/A

### PR DESCRIPTION
**Pull request by Latiah**
What does this PR do?

This PR includes notification implementation where a user will be able to view  notifications when an event is done like creating an appointment or cancelling an appointment

Description of Task to be completed?

Fetching data from the database

How should this be manually tested?

Login  the app and on the home screen click on the notification icon and from there you will find the notifications

Any background context you want to provide?

What are the relevant pivotal tracker/Trello stories?
N/A

Screenshots (if appropriate)

Questions:
N/A

### CODE REVIEW

**Review by Emmyfrank — CHANGES_REQUESTED** [review]
# Work on following comment
I think it might be better if if you work on deleting all notifications and singe notification because sometimes  a patient will need to delete them
## you can also update your PR

WhatsApp Image 2024-07-22 at 12 29 34

**Review by Emmyfrank — APPROVED** [review]
Now i can clear all notfications or single notfication , thanks for working on my comments

**Review by 911samuel — APPROVED** [review]

**Review by justinmihigo — APPROVED** [review]
Notifications are coming but if you can manage so that you can use system notifications so that a user can know immediately. but otherwise great job on this

**Comment by Latiah** [comment]
> Notifications are coming but if you can manage so that you can use system notifications so that a user can know immediately. but otherwise great job on this

thanks, @justinmihigo  I am on it

**Pull request merged**
