### PR TITLE
Feature: Sign in with google

### LINKED ISSUE #95: Feature: Sign in with google OAuth
#### Description

This is an implementation of google OAuth where a user will log in the app using their google account.

#### Tasks

- [x] Create OAuth clients in google cloud platform
- [x] Configure and enable google OAuth on supabase or setup env
- [x] Implement the OAuth flow in the designs.

#### Developer Notes

N/A

#### Related Issues

N/A

#### Definition of Done

- Any user with a google account should be able to sign in
- After signing in a user should be redirected to the home page

### PR DESCRIPTION
**Pull request by fredshema**
#### What does this PR do?

This PR includes implementation of logging in with google OAuth.

#### Description of Task to be completed?

- Create OAuth keys
- Implement login with google
- Login user or create user using supabase. 

#### How should this be manually tested?

Download the built apk [here](https://expo.dev/accounts/8_commanders/projects/medica/builds/d19d911d-c571-4984-9c88-eec6f9d53fd3) and install it.

Navigate to the login page or signup page and click login with google. There will be a popup browser, enter your Gmail credentials and click continue. Wait for a second and you should be logged in.

#### Any background context you want to provide?

The OAuth keys are loaded from env variables. If you want to test i can send them to you privately or you can create yours for testing.

#### What are the relevant pivotal tracker/Trello stories?

N/A

#### Screenshots (if appropriate)

N/A

#### Questions:

N/A

### CODE REVIEW

**Review by 911samuel — CHANGES_REQUESTED** [review]
I'm unable to continue, here is the error 
Error: Client Id property androidClientId must be defined to use Google auth on this platform., js engine: hermes

**Comment by fredshema** [comment]
@911samuel Let me send you client ids

**Review by justinmihigo — COMMENTED** [review]
I'm trying to review your work but I am getting error
Screenshot 2024-06-17 at 08 53 25
and consider rebasing

**Comment by fredshema** [comment]
@justinmihigo that issue is fixed, you can test again

**Review by justinmihigo — APPROVED** [review]
I am still getting redirected to google.com both on my android device and emulator

**Review by Latiah — APPROVED** [review]

**Comment by Latiah** [comment]
> I am still getting redirected to google.com both on my android device and emulator
me too I   was redirected to google thought I did not have latest changes

**Comment by 911samuel** [comment]
Same to me i'm being redirected to google chrome

**Review by twizerim — APPROVED** [review]

**Review by 911samuel — APPROVED** [review]
Great work! 
corrected all redirections

**Pull request merged**
