### PR TITLE
Chore: Ejecting from expo managed

### PR DESCRIPTION
**Pull request by chrysloi**
# Chore: Ejecting from expo managed

## Description

This is to eject from expo managed to enable us to run the app with the webrtc feature.

### Android
- Check if you have JDK correctly installed from terminal by running:
```
java --version
```
- If it returns like below or related you can go to next step.
   Otherwise find ways to configure JDK on the current os you're using.
> ⚠️ NB: it may vary according to OS or JDK versions
>> openjdk version "17.0.10" 2024-01-16 LTS
>> OpenJDK Runtime Environment Zulu17.48+15-CA (build 17.0.10+7-LTS)
>> OpenJDK 64-Bit Server VM Zulu17.48+15-CA (build 17.0.10+7-LTS, mixed mode, sharing)

- Clone this repo and checkout to `ch-ejecting-expo-managed`
```
git clone git@github.com:atlp-rwanda/commanders-rn-medica.git
cd commanders-rn-medica
git checkout ch-ejecting-expo-managed
npm install
```
- Now run the app
```
npm run android
```

### IOS
- Clone this repo and checkout to `ch-ejecting-expo-managed`
```
git clone git@github.com:atlp-rwanda/commanders-rn-medica.git
cd commanders-rn-medica
git checkout ch-ejecting-expo-managed
npm install
```
- install pods
```
cd ./ios
pod install
cd ../
```
- Now run the app
```
npm run ios
```

⚠️ NB: 
- If you're running ios and you have xcode less than 13.x.x it'll not work
- if you miss a step the next might not work

### CODE REVIEW

**Comment by Latiah** [comment]
hey @chrysloi  I faced this while running your pr
Screenshot 2024-07-05 at 16 30 43

**Comment by chrysloi** [comment]
> hey @chrysloi I faced this while running your pr Screenshot 2024-07-05 at 16 30 43

this seems to be compatibility issues with you JDK version please share what you get when you run `java --version` 

also share the output you get after running `npx react-native doctor`

**Comment by Latiah** [comment]
Screenshot 2024-07-05 at 18 51 03

**Comment by chrysloi** [comment]
> Screenshot 2024-07-05 at 18 51 03

@Latiah you'll need to install JDK 17 that's the suggested one as in the last versions of JDK are not supported with some of the packages. Make sure you did set the ANDROID_HOME correctly as the react-native doctor isn't finding it!

**Review by kibongos40 — CHANGES_REQUESTED** [review]
# I'm getting this warning.
### More error details at the end down
image

# If I dismiss it, the app runs well no problem

simulator_screenshot_77B78B6D-19A1-41C2-90CF-612DA19AA957


If you want to change the appearance of status bar, you have to change     UIViewControllerBasedStatusBarAppearance key in the Info.plist to YES

+[RNSScreenWindowTraits assertViewControllerBasedStatusBarAppearenceSet]
    RNSScreenWindowTraits.mm:18
-[RNSScreenView setStatusBarStyle:]
__49-[RCTComponentData createPropBlock:isShadowView:]_block_invoke_10
__49-[RCTComponentData createPropBlock:isShadowView:]_block_invoke_2.110
__49-[RCTComponentData propBlockForKey:isShadowView:]_block_invoke_2
RCTPerformBlockWithLogFunction
RCTPerformBlockWithLogPrefix
__49-[RCTComponentData propBlockForKey:isShadowView:]_block_invoke
__50-[RCTComponentData setProps:forView:isShadowView:]_block_invoke
__NSDICTIONARY_IS_CALLING_OUT_TO_A_BLOCK__
-[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:]
-[RCTComponentData setProps:forView:isShadowView:]
-[RCTComponentData setProps:forView:]
__50-[RCTUIManager createView:viewName:rootTag:props:]_block_invoke.415
__44-[RCTUIManager flushUIBlocksWithCompletion:]_block_invoke
__44-[RCTUIManager flushUIBlocksWithCompletion:]_block_invoke.484
__RCTExecuteOnMainQueue_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_drain
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
-[UIApplication _run]
UIApplicationMain
main
start_sim
0x0

**Review by Latiah — APPROVED** [review]

**Comment by Latiah** [comment]
> > Screenshot 2024-07-05 at 18 51 03
> 
> @Latiah you'll need to install JDK 17 that's the suggested one as in the last versions of JDK are not supported with some of the packages. Make sure you did set the ANDROID_HOME correctly as the react-native doctor isn't finding it!

Thanks .After setting up everything correctly I was able to run the app everything is fine I encountered 0 errors

**Comment by chrysloi** [comment]
> # I'm getting this warning.
> ### More error details at the end down
> image
> 
> # If I dismiss it, the app runs well no problem
> simulator_screenshot_77B78B6D-19A1-41C2-90CF-612DA19AA957
> 
> If you want to change the appearance of status bar, you have to change UIViewControllerBasedStatusBarAppearance key in the Info.plist to YES
> 
> +[RNSScreenWindowTraits assertViewControllerBasedStatusBarAppearenceSet] RNSScreenWindowTraits.mm:18 -[RNSScreenView setStatusBarStyle:] __49-[RCTComponentData createPropBlock:isShadowView:]_block_invoke_10 __49-[RCTComponentData createPropBlock:isShadowView:]_block_invoke_2.110 __49-[RCTComponentData propBlockForKey:isShadowView:]_block_invoke_2 RCTPerformBlockWithLogFunction RCTPerformBlockWithLogPrefix __49-[RCTComponentData propBlockForKey:isShadowView:]_block_invoke __50-[RCTComponentData setProps:forView:isShadowView:]_block_invoke **NSDICTIONARY_IS_CALLING_OUT_TO_A_BLOCK** -[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] -[RCTComponentData setProps:forView:isShadowView:] -[RCTComponentData setProps:forView:] __50-[RCTUIManager createView:viewName:rootTag:props:]_block_invoke.415 __44-[RCTUIManager flushUIBlocksWithCompletion:]_block_invoke __44-[RCTUIManager flushUIBlocksWithCompletion:]_block_invoke.484 __RCTExecuteOnMainQueue_block_invoke _dispatch_call_block_and_release _dispatch_client_callout _dispatch_main_queue_drain _dispatch_main_queue_callback_4CF **CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE** __CFRunLoopRun CFRunLoopRunSpecific GSEventRunModal -[UIApplication _run] UIApplicationMain main start_sim 0x0

@kibongos40 That's addressed, Please check again!

**Comment by 911samuel** [comment]
Screenshot from 2024-07-10 10-24-59


it it failing on my device

**Review by fredshema — APPROVED** [review]
The app is starting correctly on android. Nice work👍🏽

**Comment by Emmyfrank** [comment]
> The app is starting correctly on android. Nice work👍🏽

ok which is good

**Review by 911samuel — APPROVED** [review]
Great work! issue was on my android studion sdk now resolved

**Review by kibongos40 — APPROVED** [review]
Now it works 
simulator_screenshot_B3F6B755-040C-4B38-93C7-D4257B010B68

**Review by mukunzidd — APPROVED** [review]
LGTM

**Pull request merged**
