### PR TITLE
Feature: Video call appointment

### LINKED ISSUE #76: Feature: Video call appointment
# Feature: Video call appointment

## Description

As a As a patient I want to be able to view details on my video appointment and be able to follow it.

The Video call appointment should have the following:

- start the appointment
- View details about the appointment
- Have a visual call

### Acceptance Criteria

- [ ] User can start the video call 
- [ ] User can view details about the appointment
- [ ] User can stop the video after it's ended

## Developer Notes

- Implement the designed video appointment screens
- Add all possible functionality
- Write readable codes.

### PR DESCRIPTION
**Pull request by chrysloi**
# Feature: Video call appointment

## Description

As a As a patient I want to be able to view details on my video appointment and be able to follow it.

The Video call appointment should have the following:

- start the appointment
- View details about the appointment
- Have a visual call

### Acceptance Criteria

- [ ] User can start the video call 
- [ ] User can view details about the appointment
- [ ] User can stop the video after it's ended

## Developer Notes

- Implement the designed video appointment screens
- Add all possible functionality
- Write readable codes.

### CODE REVIEW

**Comment by Emmyfrank** [comment]
I THINK YOU CAN SOLVE YOUR BRANCH'S CONFLICTS

Screenshot 2024-05-29 at 16 43 05

**Review by Latiah — APPROVED** [review]

**Review by Latiah — APPROVED** [review]

**Review by 911samuel — APPROVED** [review]
looks great

**Comment by justinmihigo** [comment]
Great work @chrysloi . Can try to center the photo of the doctor in this circular view and blur the photo in the background or add other filters that can blur this background. and resolve the conflicts on your branch.

**Comment by chrysloi** [comment]
Hi @justinmihigo there's no conflict on my branch. and also I considered adding the blur. Thanks!

**Review by justinmihigo — APPROVED** [review]
This looks good. My bad about the conflict  saw the past screenshot.

**Review by Adadie — COMMENTED** [review]
@chrysloi just merged your branch but work on ensuring that the action buttons on the video call function properly (removing camera, audio and so on)

**Pull request merged**
