### PR TITLE
Chore: Add README.md to Repository

### LINKED ISSUE #6: Chore: Drafting README Content for the repository
# Description
This issue is dedicated to planning the content and structure of the repository's README file.
Share your ideas, suggestions, and feedback on what should be included in the README.
Let's collaborate to create a clear and informative README that shows clear understanding of the repository.

## Proposed Sections:
- [x] Title and Description
- [x] Installation
- [x] Usage

## Deadline:
30th April 2024

### PR DESCRIPTION
**Pull request by kibongos40**
# Description
This pull request adds a README.md file to the repository. The README.md file is a crucial component for any repository as it provides essential information about the project, including its purpose, installation instructions, usage guidelines, and more.

## Changes:

Added README.md file.

## Details:

The README.md includes the following sections:

1. Project Title and Description: A brief overview of the project, its goals, and what it does.
2. Installation Instructions: Step-by-step guide on how to install and set up the project locally.
3. Usage Instructions: Basic instructions on how to use the project after installation.
4. Project maintainers and leaders

### CODE REVIEW

**Comment by fredshema** [comment]
Can you squash commits into one

**Comment by Latiah** [comment]
Hey @kibongos40  can you resolve these conflicts

**Review by fredshema — APPROVED** [review]

**Review by Latiah — APPROVED** [review]

**Comment by kibongos40** [comment]
All requested changes fixed.

**Review by mukunzidd — APPROVED** [review]
These badges you added don't really help. But I guess they are fine. The badges we need need to be able to answer important questions like: Is the build passing, Are tests passing, What's the test coverage, I don't think things like TypeScript version is as important. We'll merge this but we'll need more updates in the future.

**Pull request merged**
