### PR TITLE
Feature : Write review screen

### LINKED ISSUE #80: Feature : Write review screen
### Description:
This issue is a screenwriting review after you chat with the doctor  

### What is included?

. direct is text area for writing your review
Make a choice between yes or no  and submit

### Screen shoot

67_Light_leave a review blank form (1)

68_Light_leave a review filled form

### PR DESCRIPTION
**Pull request by twizerim**
### Description:
 This is the screen where client can write a review to a doctor, and you recommend the doctor to your friends

### What do you do on this pr?

1. Using start checkbox, you can mention your experience to doctor
2. Write your review in text area
3. And recommend doctor to your friend or not by choosing between
                    . Yes
                    . No

### If you want to go to the branch where code can be pushed,

Clink to this link: [ft-write-review](https://github.com/atlp-rwanda/commanders-rn-medica/tree/ft-write-review-screen)

1. ### How do I run it?

run by : **npm start**

and go to home and choose the tab called appointment, then on upcoming, navigate to voice icon and you will see the details of using voice call to doctor. Continue to use voice call untill you stop voice call, you will see if you want to cancel or leave review, then navigate to leave review and start to write your review

### Screen shoot 
67_Light_leave a review blank form (1)

68_Light_leave a review filled form

69_Light_leave a review successful

### CODE REVIEW

**Comment by Latiah** [comment]
hey @twizerim  can you improve the description for your pr

**Review by Latiah — APPROVED** [review]

**Review by 911samuel — COMMENTED** [review]
WhatsApp Image 2024-05-31 at 09 05 40


Great work gedeon but consider double checking on font size on text as you can see the text are breaking to new line

**Review by Adadie — CHANGES_REQUESTED** [review]
Hey @twizerim, awesome work on this. Please apply the following before we can merge it:

1. The font weight of the title doesn't match the designs "How was your experience with Dr. Drake Boeson".
2. I should be able to add a review from "Appointment -> Completed -> Leave a review button"
3. The button colors don't match what's on the designs (Cancel and submit button)

**Review by 911samuel — APPROVED** [review]
Thanlk you @twizerim  for working on all feedbacks you got 
Now things looks great

**Pull request merged**
