### PR TITLE
Feature: Add onboarding screen

### LINKED ISSUE #35: Feature: Onboarding Screen
# Description: Implement Onboarding Screen

As part of enhancing the user experience for our Medica app, we need to implement an onboarding screen. The onboarding screen will serve as a welcoming introduction for new users, showcasing the key features and benefits of our app, and guiding them through the initial setup process.

### PR DESCRIPTION
**Pull request by kibongos40**
## What does this PR do?
This pull request adds a onboarding screen to the Medica app. The onboarding screen introduces users to key features and benefits of the app on launch.

## Testing
- Tested on iOS and Android devices to ensure responsive design and functionality.
- Verified swipe gestures, navigation buttons, and transitions between slides.

## Dependencies
- Uses react-native-swiper for the swipeable onboarding slides.

## Screenshots
image

image

image

### CODE REVIEW

**Comment by fredshema** [comment]
When you download images from figma try increasing the resolution to 2x, the images you have looks pixelated on a real device.

Can you also check your button padding on these pages, seems smaller than the designs


Also on this page the button looses its border radius

**Comment by kibongos40** [comment]
> When you download images from figma try increasing the resolution to 2x, the images you have looks pixelated on a real device.
> 
> Can you also check your button padding on these pages, seems smaller than the designs 
> 
> Also on this page the button looses its border radius 

Working on it

**Comment by justinmihigo** [comment]
Also change the color of the blue rectangle  that shows the current screen its too blueish on the design it is not like that, and also change the font family on the next button. use Urbanist, other wise great job after finishing all the comments reach out back to approve this.

**Review by mukunzidd — DISMISSED** [review]
- Look into @justinmihigo's feedback.
- The last onboarding screen has a rectangular get started button only on ios.

**Comment by kibongos40** [comment]
@justinmihigo @fredshema @mukunzidd issues fixed. You can review again.

**Review by Latiah — APPROVED** [review]

**Review by justinmihigo — APPROVED** [review]
if possible do an update on your screenshots in description.

**Pull request merged**
