### PR TITLE
Feature:FAQ and Help center implementation

### PR DESCRIPTION
**Pull request by Emmyfrank**
# Description
This implementation enables customers to get help  for assistance with medical services.   customers will also get the answer of questions or guideline of Medica app , where they will be geting questions and answers which are related to medica app everything are being fetched in database.
## Guide line
# After loging in navigate to Profile in the right bottom of the app icon
# Navigate to Help Center you will see FAQ
# Click on Drop down of specfic question that you have you will see  the guidance of it.
# At top righ we have also contact us you can navigate there and 
# you will see our different links where you can contact us easly Ex: throught whatsapp, instagram, facebook , tweeter and custom services

## Screenshoot Of customer  UI

Screenshot 2024-07-11 at 15 36 03

### CODE REVIEW

**Review by 911samuel — APPROVED** [review]
Yeah great!

**Review by twizerim — COMMENTED** [review]
When I am going to write message when you send it have this issue

 Screenshot_1721386028 it have this error

and make scroll to this screen the user rea

d last aswer to that last question for easily way.

**Comment by Emmyfrank** [comment]
On Fri, 19 Jul 2024 at 12:53 TWIZERIMANA Gedeon ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
>
> When I am going to write message when you send it have this issue
>
> Screenshot_1721386028.png (view on web)
> <https://github.com/user-attachments/assets/e69aabde-f38e-4eee-a622-c5530b7395aa>
> it have this error
>
There is no message implementation of message on that PR that will be
implemented on another PR that’s for FAQ and contact

**Review by twizerim — APPROVED** [review]

**Comment by Adadie** [comment]
Hey @Emmyfrank I'm encountering the below errors, also the chat is filled with messages I didn't send
Screenshot 2024-07-20 at 18 12 19

Screenshot 2024-07-20 at 18 11 02

**Comment by Emmyfrank** [comment]
Shema Fred is working on that message part on help center

**Pull request closed without merging**
