### PR TITLE
Feature:Sending-media-via-messaging implementation

### PR DESCRIPTION
**Pull request by Emmyfrank**
## Discription

This implementation enables customers to communicate with a doctor appointment with media services, chatting with a doctor by using media image and voice, audio record and messaging
1: If you don't have an account 1st register ,if you aleady have an account navigate too
2: Book appointment or navigate to appointment if you have already booked  and choose messaging appointment.
3: From there you can user text message , image,audio, and record, as a patient if your session has already started , if your session is not started they will show you a message to to describe that your session not yet started , and if your swssion has already reached on the time you scheduled , you can start chating with your doctor, if time has ended they will also show you that the session has ended .
4: the message or audio and record you sent or what you received will be different according to their color and possitions.
5:If you want to test reply , you can go in database and open messages table, check the spesfic message that you sent, and click on appointment Id, and after copy the appointment id of your message , insert new row and follow the screenshoot below to fill it  after save the message will be sent to your emirator as reply.
Screenshot 2024-07-17 at 12 20 31

Screenshot 2024-07-17 at 12 20 47

## screenshoot

Screenshot 2024-07-17 at 00 12 42

### CODE REVIEW

**Comment by fredshema** [comment]
@Emmyfrank try to rename the pr and add description on how we can test the feature. I tried to go through the feature and I noticed that messages are not differentiated. Both the doctor and patient messages looks the same and you can't tell who sent which message. I saw that messages are being auto updated that is nice. Also i don't think you noticed that you created 3 similar issues for this feature so check on which you can close

**Review by 911samuel — APPROVED** [review]
Screenshot from 2024-07-17 11-35-35


Great work!!!

**Comment by Emmyfrank** [comment]
> @Emmyfrank try to rename the pr and add description on how we can test the feature. I tried to go through the feature and I noticed that messages are not differentiated. Both the doctor and patient messages looks the same and you can't tell who sent which message. I saw that messages are being auto updated that is nice. Also i don't think you noticed that you created 3 similar issues for this feature so check on which you can close

thanks let me work on it

**Comment by Emmyfrank** [comment]
> > @Emmyfrank try to rename the pr and add description on how we can test the feature. I tried to go through the feature and I noticed that messages are not differentiated. Both the doctor and patient messages looks the same and you can't tell who sent which message. I saw that messages are being auto updated that is nice. Also i don't think you noticed that you created 3 similar issues for this feature so check on which you can close
> 
> thanks let me work on it

check again

**Comment by Emmyfrank** [comment]
> > @Emmyfrank try to rename the pr and add description on how we can test the feature. I tried to go through the feature and I noticed that messages are not differentiated. Both the doctor and patient messages looks the same and you can't tell who sent which message. I saw that messages are being auto updated that is nice. Also i don't think you noticed that you created 3 similar issues for this feature so check on which you can close
> 
> thanks let me work on it

check again

**Review by justinmihigo — APPROVED** [review]
This looks great

**Review by twizerim — APPROVED** [review]

**Comment by Adadie** [comment]
@Emmanuel262 please add loading states for when the image is being loaded

**Pull request merged**
