### PR TITLE
Feature: Facebook sign in

### LINKED ISSUE #100: Feature: Facebook Login
# Feature: Facebook Login

## Description

As a patient I want to make it easy to login or signup with facebook. instead of creating an account and forget the password or have too many accounts that are not easy to remember.

### Acceptance Criteria

- [ ] A user can login with a facebook account
- [ ] Only relevant information must be displayed
- [ ] A user can logout

## Developer Notes
- In order to test this app building may be required

## Related Issues
- N/A

### PR DESCRIPTION
**Pull request by justinmihigo**
#### What does this PR do?
- This PR setups the support of facebook login for our app, with the use of deep linking  and the help with supabase as Backend as a service.

#### Description of Task to be completed?
- With the use of supabase and facebook we have to setup a functionality to allow the user to signing with facebook
- A user can sign out 
- Build a file for android that will help us reference the app

#### How should this be manually tested?
- Open the app after cloning the repo, go to the first welcome screens click on continue with facebook then login in, after you will be brought back to the app. and continue navigating
#### Any background context you want to provide?
- Use port 8081 when running your expo because it is one that is hard coded for now.

#### Screenshots (if appropriate)
- N/A

### CODE REVIEW

**Review by 911samuel — COMMENTED** [review]
I'm unable to signin with facebook
WhatsApp Image 2024-06-17 at 17 47 40

**Comment by Latiah** [comment]
hey @justinmihigo  do we have to first build the app  to see what you worked on in this pr

**Review by twizerim — APPROVED** [review]

**Comment by twizerim** [comment]
Please solve this conflict fast

**Comment by Latiah** [comment]
@justinmihigo please rebase and solve these conflicts

**Comment by Latiah** [comment]
On my end it kept on loading I did not react the home screen

**Comment by 911samuel** [comment]
> On my end it kept on loading I did not react the home screen 

same to me but at the end i got time out
WhatsApp Image 2024-06-20 at 12 20 30

**Comment by Adadie** [comment]
@twizerim could you please provide details on how you managed to test this feature

**Review by Latiah — APPROVED** [review]

**Pull request merged**
