### PR TITLE
feature:messaging appointment implementation

### PR DESCRIPTION
**Pull request by Emmyfrank**
## Description
Implement the functionality for making appointments using messaging chat. This includes capturing user details, selecting a doctor, scheduling the appointment, and providing confirmation.

## Checklist

- [x] **Appointment Booking via Message Chat** 
  - Implement the ability for users to book appointments using text messages.
    - [x] Capture user details (name, contact info).
    - [x] Allow selection of doctor and appointment time.
    - [x] Confirm booking and send confirmation message.

## Additional Notes 
- Test the appointment booking functionality thoroughly text message.
- Follow best practices for coding standards and documentation.
- Ensure data security and privacy, especially for sensitive user information.
## screenshoots of what i will be working on.

Screenshot 2024-06-26 at 17 00 11
Screenshot 2024-06-26 at 17 00 32

## Assignees
- @Emmyfrank

### CODE REVIEW

**Comment by Latiah** [comment]
Screenshot_1720390412
hey @Emmyfrank I reviewed your work I was able to send a message that was great.
 what  you can modify is this first screen of details so that it matches what is in that appointment like the amount to be paid and the time when the appointment will start on these last buttons also check on the gender and see how you can retrieve the gender of the patient.

**Comment by Emmyfrank** [comment]
> Screenshot_1720390412 hey @Emmyfrank I reviewed your work I was able to send a message that was great. what you can modify is this first screen of details so that it matches what is in that appointment like the amount to be paid and the time when the appointment will start on these last buttons also check on the gender and see how you can retrieve the gender of the patient.

thanks for your comment , i have to consider

**Comment by Emmyfrank** [comment]
> Screenshot_1720390412 hey @Emmyfrank I reviewed your work I was able to send a message that was great. what you can modify is this first screen of details so that it matches what is in that appointment like the amount to be paid and the time when the appointment will start on these last buttons also check on the gender and see how you can retrieve the gender of the patient.

worked on gender and other and some details, the messages are working you can approove might be better to have them in today's demo

**Comment by Latiah** [comment]
> > Screenshot_1720390412 hey @Emmyfrank I reviewed your work I was able to send a message that was great. what you can modify is this first screen of details so that it matches what is in that appointment like the amount to be paid and the time when the appointment will start on these last buttons also check on the gender and see how you can retrieve the gender of the patient.
> 
> worked on gender and other and some details, the messages are working you can approove might be better to have them in today's demo

yes let me check again real quick

**Comment by Latiah** [comment]
> > Screenshot_1720390412 hey @Emmyfrank I reviewed your work I was able to send a message that was great. what you can modify is this first screen of details so that it matches what is in that appointment like the amount to be paid and the time when the appointment will start on these last buttons also check on the gender and see how you can retrieve the gender of the patient.
> 
> worked on gender and other and some details, the messages are working you can approove might be better to have them in today's demo

yeap let me do that

**Comment by Latiah** [comment]
.

**Review by Latiah — APPROVED** [review]

**Review by twizerim — APPROVED** [review]

**Review by 911samuel — APPROVED** [review]
You did amazing work!

**Comment by Adadie** [comment]
Hey @Emmyfrank, great work on the implementation but images and audio seem not to be getting uploaded!

**Comment by Emmyfrank** [comment]
Thanks and the approach that I used still harder to implement that , because I didn't use get stream,  for messaging my approach is better that get stream, on audio part and image still harder , that's why I focused on messaging

**Comment by Adadie** [comment]
@Emmyfrank I'm merging your PR but create another one for sending media via messaging

**Comment by Emmyfrank** [comment]
Thanks I have to work on it .

**Pull request merged**
