### PR TITLE
Fix: Home screen styling

### PR DESCRIPTION
**Pull request by chrysloi**
# Fix: Home screen styling

## Description

From the view of the home screen styling should be matching the design for a better aesthetic.

### Steps to Reproduce

1. Open the app an navigate to the home screen
2. Navigate through it.

**Expected Behavior:**
Selected filter text should appeal in white text, container styles match the design, images should match the design.

**Actual Behavior:**
Selected filter text not appealing, container styles not matching the design, current images not matching the design.

## Potential Causes

- Updates on other screens not applied to it.

## Related Issues

- #17 (Home & Action Menu)

### CODE REVIEW

**Review by fredshema — APPROVED** [review]

**Review by justinmihigo — COMMENTED** [review]
Resolve the conflicts

**Comment by chrysloi** [comment]
> Resolve the conflicts

Conflicts solved and also I've done squash.

**Review by justinmihigo — APPROVED** [review]

**Review by Adadie — COMMENTED** [review]
Hey @chrysloi would you add doctors under each category for someone to get data when they switch tabs. You could add different ones for someone to easily notice that the tab has changed

**Comment by chrysloi** [comment]
Hi @Adadie, this is done.

> Hey @chrysloi would you add doctors under each category for someone to get data when they switch tabs. You could add different ones for someone to easily notice that the tab has changed

**Pull request merged**
