### PR TITLE
Feature:book appointment implementation

### LINKED ISSUE #110: Feature: Book appointment implementation
This issue deals with booking an appointment.

- [ ] Patients will be able to select the time and date of the appointment.
- [ ] Patients will book a doctor they want .
- [ ] Patients will fill in the problem they have to give the doctor an overview of the appointment

### PR DESCRIPTION
**Pull request by Latiah**
What does this PR do?
This PR includes the appointment booking with a doctor implementation

Description of Task to be completed?
create appointment table on supabase
collect data from the app on the appointment screens

How should this be manually tested?

Navigate the home screen after logging in then click on one of the doctors under  top doctors on the home screen. From there you will be directed to the details of the doctor click on book appointment after you will be directed to a book appointment screen where you will choose the time and date you want an appointment to be later you will be directed to the select package screen after selecting a package and duration of the package you will se a summary of the appointment you want then you can click on next to schedule that appointment you will se a sucess message after it you will be directed to the homescreen again.

Any background context you want to provide?

Check in the **appointment** table on supabase and see if the appointment you booked is there

What are the relevant pivotal tracker/Trello stories?
N/A

Screenshots (if appropriate)
N/A

Questions:
N/A

### CODE REVIEW

**Review by justinmihigo — APPROVED** [review]
This is great but can you add this after I book an appointment, if I go to the appointments tab I should see it in upcoming

**Comment by Latiah** [comment]
> This is great but can you add this after I book an appointment, if I go to the appointments tab I should see it in upcoming

Thank you @justinmihigo  I will consider that too  I  wa trying to fix something with the doctor at the moment but I will also consider your suggestion when I am done cause the doctor will be needed too on that screen that will show upcomming appointments

**Review by twizerim — APPROVED** [review]

**Review by 911samuel — APPROVED** [review]
nice one! thank you!

**Comment by Adadie** [comment]
Hey @Latiah awesome work on this. You could make A small improvement to make the user experience much better: could you gray out the time already booked? You can understand the frustration users will get when they keep on getting already booked alerts when they click on the time button

**Comment by Latiah** [comment]
> Hey @Latiah awesome work on this. You could make A small improvement to make the user experience much better: could you gray out the time already booked? You can understand the frustration users will get when they keep on getting already booked alerts when they click on the time button

@Adadie  I am done working on  this comment

**Comment by Adadie** [comment]
Hey @Latiah I noticed after merging that the when I select a specific doctor, he's not the one that I book an appointment with. It's seems to always be Eloi Mwokolo

**Pull request merged**
