### PR TITLE
Feature: search implementation #149

### LINKED ISSUE #149: Feature: Search Implementation
## Description

As a patient, I want to have a robust and efficient search functionality so that patient can easily search doctors and tarticles and many more ...

The search functionality should support the following operations:

- Search doctor and article by name, category, or other attributes
- Filter doctor and article by category 
- Sort search results by trend, popularity, or other factors
- Provide autocomplete suggestions for search queries

### Acceptance Criteria

- [x] Users can search for doctor by name, category, or other attributes
- [x] Users can filter and sort doctor by category 
- [x] Autocomplete suggestions are provided based on user input
- [x] Sort search results by trend, popularity, or other factor

## Developer Notes

- **Search Index and Data Model**: Design and implement the search index and data model using an appropriate tool (e.g., Elasticsearch, Algolia, or similar search engine).
- **API Endpoints**: Define the API endpoints and request/response payloads for search operations.
- **Integration**: Integrate with the existing database or services to fetch doctor and article details.
- **Autocomplete**: Implement an autocomplete feature to provide suggestions based on user input.
- **Filtering and Sorting**: Implement filtering by categories and sorting by trend, popularity, or other relevant factors.
- **Edge Cases**: Handle edge cases such as no results found, invalid queries, or changes in doctor/article availability.
- **Performance Optimization**: Implement caching mechanisms for frequently accessed search results (optional) and ensure scalability and performance optimizations for high-traffic scenarios.
- **Logging and Monitoring**: Implement logging and monitoring for search operations to track search queries and results for analytics purposes.
- **Error Handling**: Ensure appropriate error handling and validation for search operations to enhance user experience.

### PR DESCRIPTION
**Pull request by 911samuel**
### What does this PR do?

This PR implements a robust and efficient search functionality for the application, allowing patients to easily search for doctors, articles, and more.

### Description of Task to be completed?

- Implement search functionality to support operations such as searching by name, category, and other attributes.
- Add filtering capabilities by category for both doctors and articles.
- Implement sorting for search results by trend, popularity, or other relevant factors.
- Provide autocomplete suggestions for search queries to enhance the user experience.

### How should this be manually tested?

1. Open the application and navigate to the search page.
2. Enter a search query for doctors or articles by name or category.
3. Verify that the search results are displayed and can be filtered by category.
4. Check that the search results can be sorted by trend, popularity, or other factors.
5. Start typing a search query and verify that autocomplete suggestions are displayed.
6. Ensure that the system handles edge cases such as no results found or invalid queries appropriately.

### Any background context you want to provide?

As a patient, having a robust and efficient search functionality is crucial for easily finding relevant doctors and articles. This enhancement aims to improve the user experience by providing comprehensive search operations, including filtering, sorting, and autocomplete suggestions.

### Screenshots (if appropriate)

[Attach relevant screenshots if applicable]

### Questions:

[Address any questions or concerns here]

### CODE REVIEW

**Review by Latiah — APPROVED** [review]

**Review by twizerim — APPROVED** [review]

**Comment by Adadie** [comment]
Hey @911samuel where can I find the sorting and search by category? Only seeing search by name only!

**Review by Emmyfrank — CHANGES_REQUESTED** [review]
Work on comments Adadie  gave you and follow feature Feature naming convention ;
check your peers naming convention on the screen bellow.
use Featue instead of using Ft

Screenshot 2024-07-22 at 12 43 25

**Comment by 911samuel** [comment]
> Work on comments Adadie gave you and follow feature Feature naming convention ; check your peers naming convention on the screen bellow. use Featue instead of using Ft
> 
> Screenshot 2024-07-22 at 12 43 25

Thank you! to highlight that, i corrected it

**Comment by Emmyfrank** [comment]
> > Work on comments Adadie gave you and follow feature Feature naming convention ; check your peers naming convention on the screen bellow. use Featue instead of using Ft
> > Screenshot 2024-07-22 at 12 43 25
> 
> Thank you! to highlight that, i corrected it

Now everything is cool , i managed to search a doctor by name and feature  you followed feature naming convention

**Review by Emmyfrank — APPROVED** [review]
thanks for working on comments i gave you

**Pull request merged**
