### PR TITLE
Feature: about doctors & Reviews  

### PR DESCRIPTION
**Pull request by Emmyfrank**
## Description
Implement a route to list all doctors with various functionalities such as about doctor, details reviers and the ability to see all reviews and their details according to doctor ID, all datas are being fetched from database.

## Checklist

- [x] **Doctors’ Reviews**
  - Implement the ability to see each doctor review based on specialty, , availability, etc.
  
- [x] **Doctor Details:**
  - Create a detailed view for each doctor.
    - [x] Include doctor's name.
    - [x] Include doctor's photo.
    - [x] Include a brief "About" section.
WhatsApp Image 2024-06-26 at 13 13 54
WhatsApp Image 2024-06-26 at 13 13 55
WhatsApp Image 2024-06-26 at 13 13 55 (1)
Screenshot 2024-06-26 at 12 57 46

  
## Additional Notes
- Ensure that the UI/UX is intuitive and user-friendly.
- Test all functionalities thoroughly to ensure they work as expected.
- Follow the best practices for coding standards and documentation.

## Assign
- @Emmyfrank

### CODE REVIEW

**Review by fredshema — APPROVED** [review]

**Review by Latiah — APPROVED** [review]

**Comment by Emmyfrank** [comment]
Thank you for your reviews

**Review by Adadie — CHANGES_REQUESTED** [review]
Hey @Emmyfrank  the total number of reviews should match the actual reviews given to the doctor

**Comment by Emmyfrank** [comment]
i worked on your comment

**Pull request merged**
