### PR TITLE
Create user profile screen

### LINKED ISSUE #20: Feat: Fill your profile screens
#### Description

As a developer, I want to create a comprehensive UI for the Fill up screen

#### Tasks

- [x] Use an image picker for profile selection
- [x] Creating the fill up screen
- [x] Use date picker

#### Definition of Done

- The user should be able to fill up the information in all fields
- The user should be able to select a photo from the gallery
image

### PR DESCRIPTION
**Pull request by justinmihigo**
#### What does this PR do?
Create user profile screen where a user must be able to fill his info about him or her.
#### Description of Task to be completed?
- [x] Design well the UI so it is the same as the figma including fonts
- [x] Using Image Picker to select image from galery
- [x] Making sure that the test pass
- [x] Using date picker for a user to pick a date of birth using react-native-modal-datetime-picker package
- [x] Using the selector to select the gender of a user using react-native-dropdown-select-list package
#### How should this be manually tested?
Clone the repo and npm install test using expo go or use emulators
#### Any background context you want to provide?
Use expo to start easily
#### Screenshot
Screenshot_20240511-084801

### CODE REVIEW

**Comment by fredshema** [comment]
Can you try to squash your commits into one?

**Review by Emmyfrank — CHANGES_REQUESTED** [review]
Work on squashing as shema has adviced another to remain with 1 commit on your branch .

**Review by 911samuel — APPROVED** [review]
great work

**Review by fredshema — APPROVED** [review]

**Review by Latiah — APPROVED** [review]

**Review by twizerim — APPROVED** [review]

**Comment by Adadie** [comment]
@justinmihigo it should be Full name not firstname. Also check on the icon colors, they should match the one on figma

**Review by Adadie — APPROVED** [review]

**Pull request merged**
