### PR TITLE
Feature profile and settings management #120

### LINKED ISSUE #120: feature:  Profile and Settings Management
## Description

As a user, I want to have a comprehensive and user-friendly profile and settings management system so that I can easily manage my personal information, preferences, and account settings.

The profile and settings management system should support the following operations:

- Edit profile information
- Manage notification preferences
- Handle payment settings
- Configure security options
- Select language preferences
- Toggle dark mode
- Access the help center
- Invite friends

### Acceptance Criteria

- [x] Users can manage their notification preferences.
- [x] Users can view and update their payment settings.
- [x] Users can configure security options such as password changes and two-factor authentication.
- [x] Users can select their preferred language from available options.
- [x] Users can toggle between light and dark mode.
- [x] Users can access the help center for support and information.
- [x] Users can send invitations to friends to join the platform.

## Developer Notes

- Define the API endpoints and request/response payloads for profile and settings operations.
- Ensure proper authentication and authorization mechanisms are in place for secure access to profile and settings.
- Implement user-friendly UI components for profile and settings management.
- Handle edge cases such as invalid input, data conflicts, or network failures.
- Ensure scalability and performance optimizations for high-traffic scenarios.

## Related Issues

- #97 (User profile integration)

### PR DESCRIPTION
**Pull request by 911samuel**
#### What does this PR do?
This PR enhances the profile and settings management system to include features for editing profile information, managing notification preferences, configuring security options, selecting language preferences, accessing the help center, and inviting friends.

#### Description of Task to be completed?
Implement UI components and backend logic for profile and settings management, focusing on the specified features. 

#### How should this be manually tested?
1. Verify that users can edit their profile information and save changes successfully.
2. Test the functionality to manage notification preferences, ensuring changes reflect correctly.
3. Verify the implementation of security options such as password changes and two-factor authentication settings.
4. Test the language preference selection feature to ensure users can choose their preferred language.
5. Ensure access to the help center is functional and provides relevant support information.
6. Test the invitation feature to verify users can send invitations to friends.

#### Any background context you want to provide?
The implementation focuses on enhancing user experience by providing robust profile and settings management capabilities while excluding payment and dark mode features to streamline development efforts.

#### Questions:
if you have any question or feedback feel free!

### CODE REVIEW

**Review by Emmyfrank — CHANGES_REQUESTED** [review]
##  you can work on country code if is possible because when you're trying to invite someone they provide that message 

WhatsApp Image 2024-06-27 at 15 14 03

##  as you have seen up there a person is not invited because country code was required , but if you com back that person you tried to invite look like has been invited even if he/she has not successfully invited

WhatsApp Image 2024-06-27 at 15 14 03 (1)

## solve your conflicts 

## squash your commits

**Review by Emmyfrank — APPROVED** [review]
now things are working well.

**Comment by fredshema** [comment]
When i try to send an invite there is an error of `WhatsApp is not installed on your device` but i have whatsapp installed.

**Review by Latiah — APPROVED** [review]

**Comment by Latiah** [comment]
The app is in french now but why does it say English here .I also faced the same issue about whatsup not being installed in my device but I thought the reason was because I was using the emulator maybe you can check that too

**Comment by 911samuel** [comment]
> 
> The app is in french now but why does it say English here .I also faced the same issue about whatsup not being installed in my device but I thought the reason was because I was using the emulator maybe you can check that too

Thank you! the issue of not opening whatsapp is due to use of emulator and maintaining language changes on profilr portal i worked on it 

Kindly review it again

**Review by fredshema — APPROVED** [review]

**Review by fredshema — CHANGES_REQUESTED** [review]
Both signin with google and signin with apple functionalities were removed. Please rebase correctly to retain previously merged functionalities

**Comment by Adadie** [comment]
I'm getting the below error and languages aren't being listed. Also, you've removed the loaders @chrysloi had added on your profile and username:

Screenshot 2024-06-28 at 14 01 21

Screenshot 2024-06-28 at 14 00 03

**Review by fredshema — APPROVED** [review]

**Comment by 911samuel** [comment]
> I'm getting the below error and languages aren't being listed. Also, you've removed the loaders @chrysloi had added on your profile and username:
> 
> Screenshot 2024-06-28 at 14 01 21 Screenshot 2024-06-28 at 14 00 03

It seems there might be an issue with Supabase where the language and other data take a long time to load, even though they exist and the authentication process has been completed up to date.

**Comment by justinmihigo** [comment]
I can't load my profile, what I suggest is to use useEffect so that these block of code can be executed once or not those much time this is what causing the endless loading, and because it is re-rendering datas every time  the userid is provided
Screenshot 2024-07-02 at 19 17 45

**Comment by 911samuel** [comment]
> I can't load my profile, what I suggest is to use useEffect so that these block of code can be executed once or not those much time this is what causing the endless loading, and because it is re-rendering datas every time the userid is provided Screenshot 2024-07-02 at 19 17 45

thank you! the issue is fixed.

kndly review it again!

**Review by justinmihigo — APPROVED** [review]
This is looks good, great job squash the commit

**Pull request merged**
