### PR TITLE
Feature: User profile integration

### LINKED ISSUE #92: Feature: User profile intergration
# Feature: User profile intergration

## Description

As a doctor or a patient I want to be able to view my Profile

The User profile should have the following:

- display the user profile details

### Acceptance Criteria

- [ ] User can view their profile details

## Developer Notes

- Integrate the user profile with Supabase
- Display available user details
- Write readable codes.

### PR DESCRIPTION
**Pull request by chrysloi**
# Feature: User profile integration

## Description

As a doctor or a patient I want to be able to view my Profile

The User profile should have the following:

- display the user profile details

### Acceptance Criteria

- [ ] User can view their profile details

## Developer Notes

- Integrate the user profile with Supabase
- Display available user details
- Write readable codes.

### CODE REVIEW

**Review by 911samuel — COMMENTED** [review]
Your implementation looks solid, well done! Everything seems to be in place except for the logout functionality, which needs to be integrated. 

Keep up the good work!

**Review by Latiah — APPROVED** [review]

**Comment by Latiah** [comment]
I used your account which already had data and it was looking good .I guess when Sam's pr is merged we will be able to add our data too. **Great work**

**Comment by chrysloi** [comment]
Hi! @911samuel, now the logout is implemented.

**Review by 911samuel — APPROVED** [review]
Great work!

**Review by twizerim — APPROVED** [review]

**Comment by Adadie** [comment]
Hey @chrysloi awesome work on the implementation.  As I was testing I noticed that the profile image isn't being displayed, let me know if this is a known issue or if there's something I have to get it to work

**Comment by chrysloi** [comment]
Images does show up except if profile wasn't filled. also I've added an avatar once no profile image

**Comment by Adadie** [comment]
@chrysloi I'm getting this error:
 ERROR  Error uploading image:  {"error": "Bucket not found", "message": "Bucket not found", "statusCode": "404"}

**Pull request merged**
