### PR TITLE
Feature: Creating user profile UI

### LINKED ISSUE #58: Feature: Creating user profile UI
# Feature: Creating user profile UI

## Description

As a As a doctor or a patient I want to view my profile and adjust some settings or actions to my account..

The user profile should have the following:

- Edit profile
- Notification settings
- Payment settings
- Security settings

### Acceptance Criteria

- [ ] User or Doctor can edit their profile
- [ ] User or Doctor can adjust notification settings
- [ ] User or Doctor can adjust payment settings
- [ ] User or Doctor can adjust security settings

## Developer Notes

- Implement the designed profile
- Add all possible functionality
- Write readable codes.

### PR DESCRIPTION
**Pull request by chrysloi**
# Feature: Creating user profile UI

## Description

As a As a doctor or a patient I want to view my profile and adjust some settings or actions to my account..

The user profile should have the following:

- Edit profile
- Notification settings
- Payment settings
- Security settings

### Acceptance Criteria

- [X] User or Doctor can edit their profile
- [X] User or Doctor can adjust notification settings
- [X] User or Doctor can adjust payment settings
- [X] User or Doctor can adjust security settings

## Developer Notes

- Implement the designed profile
- Add all possible functionality
- Write readable codes.

### CODE REVIEW

**Review by justinmihigo — APPROVED** [review]
looks good on my end rebase

**Comment by Latiah** [comment]
can screenshoots of the screens in this PR on the description.

**Review by Latiah — APPROVED** [review]

**Comment by fredshema** [comment]
- You might have added a hashtag in your pr title.
- The number field on updating profile screen is missing the country flags.
- On my end these sign in buttons changed styles, double check and make sure they look like the design.

**Comment by chrysloi** [comment]
> * You might have added a hashtag in your pr title.
> * The number field on updating profile screen is missing the country flags.
> * On my end these sign in buttons changed styles, double check and make sure they look like the design.
> 
> 

@fredshema
the # is removed.

the input I changed it as first you'll have selected the country and you can automatically get the country code so adding the other selector of the flags would be repeating.

this screen I am not the one who worked on it and not a shared component that might have changed it.

**Review by twizerim — APPROVED** [review]

**Pull request merged**
