### PR TITLE
Feature: Sign Up and Sign In

### PR DESCRIPTION
**Pull request by 911samuel**
#### What does this PR do?
This PR adds the SignUp and SignIn screens with the active state.

#### Description of Task to be completed?
- Created SignUp screen with email and password input fields.
- Added SignIn screen with email and password input fields.
- Implemented active state for the input fields.

#### How should this be manually tested?
1. Run the app.
2. Navigate to the SignUp screen.
3. Verify that the email and password input fields are present.
4. Verify that the input fields change color when focused.
5. Verify that the Sign up button changes color when any input field is active.
6. Navigate to the SignIn screen.
7. Verify that the email and password input fields are present.
8. Verify that the input fields change color when focused.
9. Verify that the Sign in button changes color when any input field is active.

#### Any background context you want to provide?
These changes enhance the user experience by providing visual feedback when the input fields are active.

#### Screenshots
<div style="display: flex; flex-direction: row;">
  SignUp Screen
  SignIn Screen
  Active SignUp Screen
</div>

#### Questions:
Any questions or concerns about the changes?

### CODE REVIEW

**Review by justinmihigo — CHANGES_REQUESTED** [review]
Squash commits and change the font to the urbanistRegular

**Comment by Adadie** [comment]
@911samuel replace the current screen that has texts with your first screen. When someone signs in or completes setting profile they should be redirected to homepage

**Comment by 911samuel** [comment]
> Squash commits and change the font to the urbanistRegular

thank you @justinmihigo  for your valuable feed back i'm done with squashing commits i also used Urbanist as font family

please kindly review my work!!

thank you!

**Comment by 911samuel** [comment]
> @911samuel replace the current screen that has texts with your first screen. When someone signs in or completes setting profile they should be redirected to homepage

thank you @Adadie   i worked on your feed back

please kindly review my work!!

thank you!

**Comment by justinmihigo** [comment]
#### change those fonts inside the buttons and inputs and change the buttons to look like those in figma change the color and font
WhatsApp Image 2024-05-19 at 11 54 33
WhatsApp Image 2024-05-19 at 11 54 33 (1)
#### on this screen add some padding between those 3 buttons that have those icons of google apple and facebook
WhatsApp Image 2024-05-19 at 11 54 34

**Comment by 911samuel** [comment]
> #### change those fonts inside the buttons and inputs and change the buttons to look like those in figma change the color and font
> WhatsApp Image 2024-05-19 at 11 54 33 WhatsApp Image 2024-05-19 at 11 54 33 (1)
> 
> #### on this screen add some padding between those 3 buttons that have those icons of google apple and facebook
> WhatsApp Image 2024-05-19 at 11 54 34


Thanks! I didn't realize that happened while resolving some conflicts, but it's now resolved.

**Comment by Latiah** [comment]
Hey @911samuel  can you use the icons that are in the Figma designs  like those icons in the input fields in your designs they are not the same as the one on the figma designs and also consider updating the photos on the description with the current changes you have. Check on the remember me checkbox too the border radius needs a little adjustment..Anyways you did an amazing work

**Comment by 911samuel** [comment]
> Hey @911samuel can you use the icons that are in the Figma designs like those icons in the input fields in your designs they are not the same as the one on the figma designs and also consider updating the photos on the description with the current changes you have. Check on the remember me checkbox too the border radius needs a little adjustment..Anyways you did an amazing work

Thank you for your feedback, @Latiah. I've carefully reviewed my work and made the requested changes. Initially, I used vector icons, but they didn't match the icons in the Figma designs. So, I reverted back to using the icons from the Figma designs. Could you please review my work again to ensure everything aligns with the requirements? Appreciate your time and feedback!

**Review by Latiah — APPROVED** [review]

**Comment by 911samuel** [comment]
> > #### change those fonts inside the buttons and inputs and change the buttons to look like those in figma change the color and font
> > WhatsApp Image 2024-05-19 at 11 54 33 WhatsApp Image 2024-05-19 at 11 54 33 (1)
> > #### on this screen add some padding between those 3 buttons that have those icons of google apple and facebook
> > WhatsApp Image 2024-05-19 at 11 54 34
> 
> Thanks! I didn't realize that happened while resolving some conflicts, but it's now resolved.

**Review by fredshema — APPROVED** [review]
Seems good on my end. Nice work👏

**Review by Adadie — CHANGES_REQUESTED** [review]
1. Replace the screen that has dummy texts with your first screen
2. When someone signs in redirect them to the homepage
3. When some finishes filling in profile upon sign up redirect them to homepage as well

**Comment by 911samuel** [comment]
> 1. Replace the screen that has dummy texts with your first screen
> 2. When someone signs in redirect them to the homepage
> 3. When some finishes filling in profile upon sign up redirect them to homepage as well

1. I believe the screen with dummy text should be replaced with the onboarding screen for now.
2. Since the home screen hasn't been implemented yet, I can't reference it.
3. @justinmihigo is responsible for the profile screens.

**Comment by 911samuel** [comment]
> > 1. Replace the screen that has dummy texts with your first screen
> > 2. When someone signs in redirect them to the homepage
> > 3. When some finishes filling in profile upon sign up redirect them to homepage as well
> 
> 1. I believe the screen with dummy text should be replaced with the onboarding screen for now.
> 2. Since the home screen hasn't been implemented yet, I can't reference it.
> 3. @justinmihigo is responsible for the profile screens.

I didn't know that they worked on home, so by now after sign in user is redirected to home

**Pull request merged**
