### PR TITLE
Feature: book doctor appointments screens

### LINKED ISSUE #46: Feature: Doctor appointment (Booking for online consultation) screens
#### Description

A user can book a doctor consultation and select the most convenient time a doctor is available. They can also select a package that is affordable.

#### Tasks

- [x] Design doctor details screen
- [x] Design ratings & reviews screen
- [x] Design book appointment screen
- [x] Design Packages screen
- [x] Design Patients details screen 

#### Developer Notes

N/A

#### Related Issues

- N/A

#### Definition of Done

- All screens looks and behaves as the designs
- Navigation between pages works correctly

### PR DESCRIPTION
**Pull request by fredshema**
#### What does this PR do?

This PR includes designs of booking an appointment with a doctor

#### Description of Task to be completed?

- Design doctor details screen
- Design ratings & reviews screen
- Design book appointment screen
- Design Packages screen
- Design Patients details screen 

#### How should this be manually tested?

Navigate to the home page and scroll down. Click on one doctor to view their details. At the bottom you can view the reviews of a doctor click on see all to  list all reviews. After that go back one step and click on `Book Appointment` button, a list of available hours and a calendar will show. Click on `Next` button to go to the page for selecting packages and finally click on `Next` Button to go to the patient details page

#### Any background context you want to provide?

The calendar component provides a prop for rendering custom header as its default is a little different from our design but it doesn't provide the proper function to change months while clicking on the icons. I changed the icons look but their position remains the same.

#### What are the relevant pivotal tracker/Trello stories?

N/A

#### Questions:

N/A

### CODE REVIEW

**Review by justinmihigo — APPROVED** [review]
Looks great

**Review by chrysloi — CHANGES_REQUESTED** [review]
> Please do check these. same on home screen seems that are some things that disappeared.

Screen Shot 2024-05-16 at 21 40 00

**Comment by fredshema** [comment]
@chrysloi I pushed some new changes, but i found that you removed the primary color that is why some content that used it were not being displayed. Also i fixed some issues with android displaying svg based icons wrong by adding a color class.

**Comment by chrysloi** [comment]
> @chrysloi I pushed some new changes, but i found that you removed the primary color that is why some content that used it were not being displayed. Also i fixed some issues with android displaying svg based icons wrong by adding a color class.

You did a good Job @fredshema. Double check the styling on the name of the doctor that's in details and work on avoiding selecting past dates on the calendar.

**Comment by Latiah** [comment]
hey @fredshema  can you change the photos you are using as they suggested to make it look more like African

**Comment by fredshema** [comment]
> > @chrysloi I pushed some new changes, but i found that you removed the primary color that is why some content that used it were not being displayed. Also i fixed some issues with android displaying svg based icons wrong by adding a color class.
> 
> You did a good Job @fredshema. Double check the styling on the name of the doctor that's in details and work on avoiding selecting past dates on the calendar.

@chrysloi I updated the styles on the doctor and disabled previous dates from being selected in the calendar

**Comment by fredshema** [comment]
> hey @fredshema can you change the photos you are using as they suggested to make it look more like African

@Latiah Thanks, i changed the faces to reflect African faces. I will be updating the description screenshots too

**Review by Latiah — APPROVED** [review]

**Review by Adadie — CHANGES_REQUESTED** [review]
Work on the following ASAP:

1. The calendar navigation buttons are missing
2. When I select a date on the calendar I can't select a previous one i.e When I select 20th, I am unable to select 18th
3. Inputs in patient details can't be updated
4. The age field is a dropdown not input
5. Fix spacing on the hours selection section

**Pull request merged**
