### PR TITLE
Feature write your review implemetation

### LINKED ISSUE #136: Feature: Write your review to a doctor
**How does this pr do?**
In this practice, the patient should be able to see their appointment be completed for some reason, like when the appointment passes or when the time of the appointment is up. and they should be able to write a review for the doctor.

**How can you review this pr?**
Visit your appointment After logging in to the appointment tab, you can see an upcoming, completed and canceled appointment Choose the tab called completed and see your appointment as completed. According to your choice, you can go to book appointment again by clicking on the book button again and to write a review by clicking on button called leave review

**This explanation is related to this screen shot.**

### PR DESCRIPTION
**Pull request by twizerim**
**How does this pr do?**
In this practice, the patient should be able to see their appointment be completed for some reason, like when the appointment passes or when the time of the appointment is up. and they should be able to write a review for the doctor.

**How can you review this pr?**
Visit your appointment After logging in to the appointment tab, you can see an upcoming, completed and canceled appointment Choose the tab called completed and see your appointment as completed. According to your choice, you can go to book appointment again by clicking on the book button again and to write a review by clicking on button called leave review

### CODE REVIEW

**Comment by Emmyfrank** [comment]
Solving your conflict , and use Feature convention on your PR instead of using  ft

**Review by 911samuel — APPROVED** [review]
Great work!

**Review by Latiah — APPROVED** [review]

**Comment by Emmyfrank** [comment]
## You can add number of reviews for each doctor on home

Screenshot 2024-07-22 at 19 03 45

## You can Work of those Dammy number of reviews at the Top of the screen .

Screenshot 2024-07-22 at 19 01 24

## Screen of providing stars after appo

**Review by Emmyfrank — CHANGES_REQUESTED** [review]
## You can add number of reviews for each doctor on home

Screenshot 2024-07-22 at 19 03 45

## You can Work of those Dammy number of reviews at the Top of the screen .

Screenshot 2024-07-22 at 19 01 24

## You can also Update your Branch

**Comment by twizerim** [comment]
hey @Emmyfrank  i was completed your feedback, seen in this screenshot

Screenshot_1721717265

**Review by Emmyfrank — APPROVED** [review]
good job

**Comment by Adadie** [comment]
Hey @twizerim I'm encountering this error on your app. Let me know if you know how to resolve it
Screenshot 2024-07-24 at 14 45 12

**Comment by twizerim** [comment]
@Adadie I don't know the reason of that error but in local i have different error to these

**Comment by Latiah** [comment]
> Hey @twizerim I'm encountering this error on your app. Let me know if you know how to resolve it Screenshot 2024-07-24 at 14 45 12
 Hey @Adadie I helped @twizerim  review his work again but it is running on my end

**Pull request merged**
