### PR TITLE
Ft- updating and cancel appointment

### LINKED ISSUE #114: Feature: Updating and cancel appointment
### **What does this pr do?**
At this practice, the user can be able to reschedule appointment or cancel it for some reason.

### How to navigate and make to this pr
First, sign in and navigate to home. Then got to appointment  to the upcoming you see cancel appointment then cancel it
and when you want to reschedule your appointment

### How to test if a task completed.

1. You got appointment and you see if your appointment is changed
2. Got to appointment and navigated to cancel tab and saw your appointment canceled

### PR DESCRIPTION
**Pull request by twizerim**
**#### What does this pr do ?**

This practice is about when a patient want to update or cancel his or her appointment

### Required in this pr

1. First, login to your account and update your account in order to be patient
2. Book any appointment if you have not already booked 

### How to view this pr 
After logging in, go to your appointment. You will see your appointment booked; if not, go to the doctor to view her or his appointment and book an appointment. so in the appointment, you see button fro cancel and reschedule appointments, and then start to cancel or reschedule according to your choice

### How to test this

1. If you finish canceling an appointment, you see it removed in upcoming and it is going to cancelled
2. If you finish to reschedule appointment you will see the date and time can be changed on appointment found in upcoming

### CODE REVIEW

**Comment by Latiah** [comment]
Hey @twizerim  rebase so that I can review your work .you still have the other error of WebRTC

**Review by 911samuel — CHANGES_REQUESTED** [review]
WhatsApp Image 2024-07-05 at 08 07 05


same here

**Comment by Latiah** [comment]
hey @twizerim  I reviewed your work here I was able to reschedule and cancel an appointment. But here  are few things you need to change on this screen  you can use the correct icon as this was a messaging appointment you can also consider removing the zeros  for seconds  on time
Screenshot_1720476465

**Review by 911samuel — APPROVED** [review]
Great work! able to cancel and also reschedule

**Review by Latiah — APPROVED** [review]

**Comment by twizerim** [comment]
> hey @twizerim I reviewed your work here I was able to reschedule and cancel an appointment. But here are few things you need to change on this screen you can use the correct icon as this was a messaging appointment you can also consider removing the zeros for seconds on time Screenshot_1720476465

Thanks, @Latiah, for your suggestions. i have been done it now and it is correct

**Pull request merged**
