### PR TITLE
Feature: doctors detail implementation 

### PR DESCRIPTION
**Pull request by Emmyfrank**
# Doctor detail Feature

## What this PR do?
The Doctor Card feature is designed to display information about doctors in a visually appealing and user-friendly manner. This component is useful for healthcare-related applications where users need to view details about different doctors, such as their name, specialty, affiliated hospital, and reviews.

## Features
- [x] **Doctor Name**: Displays the name of the doctor.
- [x] **Role**: Shows the specialty or role of the doctor (e.g., Cardiologist, Neurologist).
- [x] **Hospital**: Indicates the hospital or medical institution where the doctor practices.
- [x] **Image**: Includes a profile picture or avatar of the doctor.
- [x] **Ratings**: Displays the doctor's rating using a star system.
- [x] **Reviews**: Shows the number of reviews the doctor has received.

## Integration and Database Interaction
This feature integrates with a Supabase backend to save and retrieve doctor information from a PostgreSQL database.

## Screenshoot
Screenshot 2024-06-13 at 21 43 28

### CODE REVIEW

**Review by 911samuel — CHANGES_REQUESTED** [review]
When user navigate to see all doctors the doctors image are not displayed same to my favorite doctors

**Review by Latiah — APPROVED** [review]

**Review by 911samuel — APPROVED** [review]
Great work!!

**Comment by Emmyfrank** [comment]
> When user navigate to see all doctors the doctors image are not displayed same to my favorite doctors

# reply
everything fixed

**Comment by Adadie** [comment]
Create another PR to display all the info on the single doctor screen

**Pull request merged**
